### PR TITLE
billit tags client

### LINKED ISSUE #32: `Tags` methods

### PR DESCRIPTION
**Pull request by phemmylintry**
closes #32

### CODE REVIEW

**Comment by phemmylintry** [comment]
@akalipetis @parisk Please review. Thanks

**Comment by parisk** [comment]
@phemmylintry can you resolve the conflicts please?

**Comment by phemmylintry** [comment]
conflict resolvd @parisk

**Review by parisk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
